server:
  port: 8030
spring:
  application:
    name: client
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
#menu中与数据库交互将数据传给服务消费者，因此它不需要与数据库交互。

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      perfer-ip-address: true

