server:
  port: 8761
eureka:
  client:
    service-url:
      #注册中心的访问地址
      defaulttZone: http://localhost:8761/eureka/
      #是否注册它自己
    register-with-eureka: false
    #是否从其他的注册中心导入数据
    fetch-registry: false